---
- name: Test SSH připojení
  hosts: all
  connection: network_cli
  gather_facts: no

  tasks:
    - name: test add DNS
      routeros_command:
        commands:
        - /ip dns set servers=1.1.1.1,8.8.8.8
