---
- name: Test SSH připojení
  hosts: all
  connection: network_cli
  gather_facts: false
  
  vars:
   ansible_network_os: routeros
   ansible_user: admin
  
  tasks:
    - name: test add DNS
      routeros_command:
        commands:
        - /ip dns set servers=8.8.8.8,1.1.1.1
