---
- name: Test SSH připojení
  hosts: all
  connection: network_cli
  gather_facts: false
  
  vars:
   ansible_network_os: routeros
   ansible_user: admin
  
  tasks:
    - name: Otestovat dostupnost hostu
      ping:
